import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { parseDocument, teiElementsByLocal } from "../../docs/js/editor/tei-document.js";
import { editCellCore, parseEdition } from "../../docs/js/editor/edition.js";
import { readingCellVisible, readingSeparator } from "../../docs/js/editor/reading-policy.js";
import { createWitness, deleteWitness, resolveWitnessReading, updateWitness, updateWitnessXml, updateReadingWitnesses, witnessInventory, witnessReadingPolicy } from "../../docs/js/editor/witness-model.js";
import { validateWithSchemas } from "../../docs/js/editor/schema-validation.js";

const wrap = (body, witnesses = '<listWit><witness xml:id="A">Alpha &amp; one</witness><listWit xml:id="group"><witness xml:id="B">Beta</witness><witness xml:id="C">Gamma</witness></listWit><witness xml:id="D">Delta</witness></listWit>') => `<TEI xmlns="http://www.tei-c.org/ns/1.0"><teiHeader><fileDesc><titleStmt><title>Synthetic witnesses</title></titleStmt><publicationStmt><p>Original test.</p></publicationStmt><sourceDesc><p>Invented source.${witnesses}</p></sourceDesc></fileDesc></teiHeader><text><body><p>${body}</p></body></text></TEI>`;
const raw = wrap('Before <app xml:id="app1"><lem wit="#A">base</lem><rdgGrp><rdg wit="#B">variant</rdg><rdg wit="#C"/></rdgGrp></app> after.');
const doc = parseDocument(raw), inventory = witnessInventory(doc);
assert.equal(witnessInventory(doc), inventory, 'Inventory is cached by immutable document identity.');
assert.equal(inventory.witnesses.length, 4);
assert.deepEqual(inventory.witnesses.find((item) => item.id === 'B').groups, ['group']);
assert.equal(inventory.apparatus[0].readings.length, 3);
assert.equal(resolveWitnessReading(doc, inventory.apparatus[0], 'B').status, 'selected');
assert.equal(resolveWitnessReading(doc, inventory.apparatus[0], 'C').status, 'omission');
assert.equal(resolveWitnessReading(doc, inventory.apparatus[0], 'D').status, 'missing');
assert.equal(resolveWitnessReading(doc, inventory.apparatus[0], 'absent').status, 'unknown-witness');
const read = (state, id = '', variant = 'dipl') => {
  const policy = witnessReadingPolicy(state.doc, id);
  const cells = state.cells.filter((cell) => readingCellVisible(cell, variant, policy));
  return cells.map((cell, index) => readingSeparator(state.doc, cells[index - 1], cell, variant, policy) + cell.text).join('');
};
const state = parseEdition(raw);
assert.equal(read(state), 'Before base after.');
assert.equal(read(state, 'B'), 'Before variant after.');
assert.equal(read(state, 'C'), 'Before  after.');
assert.equal(read(state, 'D'), 'Before  after.');
assert.equal(state.doc.raw, raw, 'Witness projection never changes source bytes.');
const variantCell = state.cells.find((cell) => cell.text === 'variant');
assert.equal(editCellCore(state, variantCell.id, 'changed').doc.raw, raw.replace('>variant<', '>changed<'), 'Displayed witness cells retain exact source offsets.');
assert.equal(updateWitness(doc, 'A', { id: 'A', description: 'Alpha & one' }), doc, 'Semantic no-op retains entity spellings.');
assert.equal(updateWitness(doc, 'A', { description: 'New <description>' }).raw, raw.replace('Alpha &amp; one', 'New &lt;description&gt;'));
assert.throws(() => updateWitness(doc, 'A', { id: 'other' }), /referenced/);
assert.throws(() => deleteWitness(doc, 'A'), /referenced/);
assert.throws(() => createWitness(doc, { id: 'A', description: 'Duplicate' }), /already exists/);
assert.throws(() => createWitness(doc, { id: 'bad id', description: 'Invalid' }), /valid XML/);
assert.throws(() => createWitness(doc, { id: 'E', description: 'Ambiguous destination' }), /Choose the witness list/);
const added = createWitness(doc, { id: 'E', description: 'Epsilon', listKey: inventory.lists[0].key });
assert.ok(added.raw.includes('<witness xml:id="E">Epsilon</witness>'));
assert.equal(deleteWitness(added, 'E').raw, raw);
assert.equal(updateWitness(doc, 'D', { id: 'unused' }).raw, raw.replace('xml:id="D"', 'xml:id="unused"'));
assert.throws(() => updateWitness(added, inventory.witnesses[0], { description: 'stale' }), /document changed/);

const groupDoc = parseDocument(wrap('<app><lem>Base</lem><rdg wit="#group">Shared</rdg></app>'));
assert.equal(resolveWitnessReading(groupDoc, witnessInventory(groupDoc).apparatus[0], 'B').status, 'selected');
assert.throws(() => deleteWitness(groupDoc, 'B'), /referenced witness group/);
const ambiguous = parseDocument(wrap('<app><lem wit="#A">x</lem><rdgGrp><rdg wit="#A">y</rdg></rdgGrp></app>'));
assert.equal(resolveWitnessReading(ambiguous, witnessInventory(ambiguous).apparatus[0], 'A').status, 'ambiguous');
const fragment = parseDocument(wrap('<app><rdg wit="#A"><lacunaEnd/>Return</rdg><rdg wit="#B"><witEnd/></rdg></app>'));
assert.deepEqual(resolveWitnessReading(fragment, witnessInventory(fragment).apparatus[0], 'A').markers, ['lacunaEnd']);
assert.equal(resolveWitnessReading(fragment, witnessInventory(fragment).apparatus[0], 'B').status, 'fragment-boundary');
const grouped = parseEdition(wrap('<app><rdgGrp><lem>Nested base</lem><rdg wit="#B">Other</rdg></rdgGrp></app>'));
assert.equal(read(grouped), 'Nested base');
const nested = parseEdition(wrap('<app><lem wit="#A">Alpha</lem><rdg wit="#B">Beta <choice><orig>vnd</orig><reg>und</reg></choice><app><rdg wit="#B"> inner</rdg><rdg wit="#A"> hidden</rdg></app></rdg></app>'));
assert.equal(read(nested, 'B'), 'Beta vnd inner');
assert.equal(read(nested, 'B', 'norm'), 'Beta und inner');
const foreign = parseDocument(wrap('<app xmlns:x="urn:foreign"><lem wit="#A">a</lem><rdg x:wit="#B">b</rdg></app>'));
assert.equal(resolveWitnessReading(foreign, witnessInventory(foreign).apparatus[0], 'B').status, 'missing');
const unlicensedGroup = parseDocument(wrap('<app><rdgGrp wit="#B"><rdg>b</rdg></rdgGrp></app>'));
assert.equal(resolveWitnessReading(unlicensedGroup, witnessInventory(unlicensedGroup).apparatus[0], 'B').status, 'missing');
const based = parseDocument(wrap('<app xml:base="other.xml"><rdg wit="#A">a</rdg></app>'));
assert.equal(resolveWitnessReading(based, witnessInventory(based).apparatus[0], 'A').status, 'missing');
assert.deepEqual(witnessInventory(based).unresolved, ['#A']);
const encoded = parseDocument(wrap('<app><rdg wit="#%41">a</rdg></app>'));
assert.equal(resolveWitnessReading(encoded, witnessInventory(encoded).apparatus[0], 'A').status, 'selected');
const duplicate = parseDocument(wrap('<app><rdg wit="#A">a</rdg></app>', '<listWit><witness xml:id="A">one</witness><witness xml:id="A">two</witness></listWit>'));
assert.ok(witnessInventory(duplicate).witnesses.every((record) => !record.unique));
assert.equal(resolveWitnessReading(duplicate, witnessInventory(duplicate).apparatus[0], 'A').status, 'unknown-witness');
const mixed = parseDocument(wrap('<ref target="other.xml#A">reference</ref>', '<listWit><witness xml:id="A">A <hi>rich</hi> description</witness><witness xml:id="B">B</witness></listWit>'));
assert.equal(witnessInventory(mixed).witnesses[0].editable, false);
assert.equal(updateWitness(mixed, 'A', { description: 'A rich description' }), mixed);
assert.throws(() => updateWitness(mixed, 'A', { description: 'flattened' }), /structured XML/);
assert.throws(() => deleteWitness(mixed, 'A'), /referenced/);
const front = parseEdition(wrap('Text', '').replace('<body>', '<front><listWit><witness xml:id="F">Witness metadata</witness></listWit></front><body>'));
assert.equal(read(front), 'Text');
const created = createWitness(parseDocument(wrap('Text', '')), { id: 'first', description: 'First witness' });
assert.equal(deleteWitness(created, 'first').raw, wrap('Text', ''));
const prefixed = parseDocument(wrap('Text', '').replace('xmlns=', 'xmlns:t=').replace(/<(\/?)([A-Za-z][A-Za-z0-9]*)(?=[\s/>])/gu, '<$1t:$2'));
const createdPrefixed = createWitness(prefixed, { id: 'P', description: 'Prefixed' });
assert.ok(createdPrefixed.raw.includes('<t:listWit><t:witness xml:id="P">'));
assert.equal(teiElementsByLocal(createdPrefixed.root, 'witness').length, 1);
const { XmlDocument } = await import('../../docs/vendor/libxml2-wasm/lib/index.mjs');
const wellFormed = (value) => {
  try { const parsed = XmlDocument.fromString(value); parsed.dispose(); return { ok: true }; }
  catch (error) { return { ok: false, message: error.message }; }
};
const richXml = '<witness xml:id="A">A <hi rend="italic">rich</hi> description</witness>';
const changedXml = updateWitnessXml(mixed, 'A', richXml, wellFormed);
assert.equal(changedXml.raw, mixed.raw.replace('<witness xml:id="A">A <hi>rich</hi> description</witness>', richXml));
assert.equal(updateWitnessXml(changedXml, 'A', richXml), changedXml, 'Exact XML no-op retains the same document.');
assert.throws(() => updateWitnessXml(mixed, 'A', richXml), /well-formedness check/);
assert.throws(() => updateWitnessXml(mixed, 'A', '<witness xml:id="A"><hi>Broken</witness>', wellFormed));
assert.throws(() => updateWitnessXml(mixed, 'A', richXml.replace('xml:id="A"', 'xml:id="new"'), wellFormed), /referenced/);
assert.throws(() => updateWitnessXml(mixed, 'A', richXml.replace('xml:id="A"', 'xml:id="B"'), wellFormed), /duplicated|already defined/);
assert.throws(() => updateWitnessXml(mixed, 'A', `${richXml}<witness xml:id="extra">Extra</witness>`, wellFormed), /exactly the selected/);
const firstApp = inventory.apparatus[0], firstReading = { node: firstApp.readings[0] };
assert.equal(updateReadingWitnesses(doc, firstApp, firstReading, ' #A '), doc);
const attributed = updateReadingWitnesses(doc, firstApp, firstReading, '#A #D');
assert.equal(attributed.raw, raw.replace('<lem wit="#A">', '<lem wit="#A #D">'));
assert.throws(() => updateReadingWitnesses(doc, firstApp, firstReading, '#notDefined'), /unique local definition/);
assert.throws(() => updateReadingWitnesses(doc, firstApp, firstReading, 'external.xml#A'), /unique local definition/);
assert.equal(updateReadingWitnesses(doc, firstApp, firstReading, '').raw, raw.replace(' wit="#A"', ''));
const opaque = parseDocument(raw.replace('<lem wit="#A">', '<lem wit="external.xml#unknown  #A #A">'));
const opaqueApp = witnessInventory(opaque).apparatus[0], opaqueReading = { node: opaqueApp.readings[0] };
assert.equal(updateReadingWitnesses(opaque, opaqueApp, opaqueReading, 'external.xml#unknown #A'), opaque);
assert.ok(updateReadingWitnesses(opaque, opaqueApp, opaqueReading, 'external.xml#unknown #A #D').raw.includes('wit="external.xml#unknown #A #D"'));
const schema = readFileSync(new URL('../../docs/schemas/tei-p5-4.11.0/tei_all.rng', import.meta.url), 'utf8');
for (const candidate of [raw, added.raw, created.raw, createdPrefixed.raw, fragment.raw]) {
  const result = await validateWithSchemas(candidate, [{ name: 'TEI All', type: 'relaxng', text: schema }]);
  assert.ok(result.every((item) => item.status === 'valid'), JSON.stringify(result));
}
console.log('Witness CRUD, group attribution, missing/ambiguous/empty readings, fragment markers, exact offsets, namespace preservation and TEI All passed.');
